version: 0.2

phases:
  install:
    commands:
      - echo Build started on `date`
      - apt-get update
      - npm config set loglevel error
      - npm i
  build:
    commands:
      - npm run production
artifacts:
  files:
    - ./dist/*