version: 0.2

phases:
  install:
    commands:
      - echo Build started on `date`
      - apt-get update
      - npm config set loglevel error
      - npm i
  build:
    commands:
      - npm run production
  post_build:
    commands:
      - cd dist
      - ls -l
      - aws s3 sync . s3://hootenanny-ui/